# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
# Deprecated alias: remove after 2026-06-30. Use config/service/runtime-telemetry.yaml.
imports:
  - { resource: runtime-telemetry.yaml }
