Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
services:
  App\Service\Runtime\RuntimeTelemetryDirInspector:
    arguments:
      $dir: '%runtime_supercharger_telemetry_dir%'

  App\Service\Runtime\RuntimeStatusProvider:
    arguments:
      $telemetryDir: '%runtime_supercharger_telemetry_dir%'

  App\Http\Runtime\RuntimeStatusController:
    arguments:
      $provider: '@App\Service\Runtime\RuntimeStatusProvider'
      $inspector: '@App\Service\Runtime\RuntimeTelemetryDirInspector'
