apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: runtime-supercharger-scrape
  labels:
    app: runtime-supercharger
spec:
  selector:
    matchLabels:
      app: runtime-supercharger
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
