Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
runtime_supercharger_telemetry_sink:
  driver: file
  dir: var/runtime/telemetry
  worker_id_env: RUNTIME_WORKER_ID
  flush_interval_sec: 1.0
