# Copyright (c) 2025 Oleksandr Tishchenko / Marketing America Corp
runtime_telemetry_metrics:
  path: /metrics
  controller: App\Http\Runtime\RuntimeMetricsController::metrics
  methods: [GET]

runtime_telemetry_aggregate:
  path: /runtime/metrics/aggregate
  controller: App\Http\Runtime\RuntimeMetricsController::aggregate
  methods: [GET]
